/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef SCALARVALUES_H
#define SCALARVALUES_H

/* function declarations */
void init_scalarValues(void);
Netsnmp_Node_Handler handle_hostVersionString;
Netsnmp_Node_Handler handle_hostValueSnmpSignal;
Netsnmp_Node_Handler handle_hostSizeDisk;

#endif /* SCALARVALUES_H */
