/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

/*
Do not forget to include all important headers
*/
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "scalarValues.h"
#include <libpq-fe.h>
#include <stdio.h>
#include <ftw.h>
#include <stdlib.h>
#include<string.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


#define scalarValuesLen	300
/** Initializes the scalarValues module */
char softwareVersion[scalarValuesLen];
char snmpSignalValue[scalarValuesLen];
char diskSpace[scalarValuesLen];

unsigned int total = 0;
char str[2000];


/* sum function to compute and add the size of individual file sizes */

int sum(const char *fpath, const struct stat *sb, int typeflag) {
    total += sb->st_size;
    return 0;
}

/* driver function to computer the disk space of "/var/log" */
char* getDiskSpace(){
    total = 0;
    if (access("/var/log", R_OK)) {
        return "1";
    }
    if (ftw("/var/log", &sum, 1)) {
        perror("ftw");
        return "2";
    }
   sprintf(str, "%d", total);
    return str;
}
/* driver function to retrieve signal value from Afiniti Test Database */

char* getSignalsValue(){
    int size = 250; 
    char *query = (char *)malloc(sizeof(char)*size); /*Stored in heap segment*/
    *(str+249) = '\0';   
    PGconn *conn= PQconnectdb("user=rehan password=123 dbname=AFINITITEST"); /* username is set as rehan, password as '123' and  database name as AFINITITEST */
    if (PQstatus(conn) == CONNECTION_BAD) {
        strcpy(query, "Connection to database failed\n"),
        PQerrorMessage(conn);
    } 
    else {
    PGresult *res = PQexec(conn, "SELECT SIGNALVALUE FROM SNMPSIGNALS ORDER BY SIGNALTIME DESC  LIMIT 1 "); /*PQexec function to execute query */
        if (PQresultStatus(res) != PGRES_TUPLES_OK) {
            strcpy(query, "No data retrieved\n"); /*error handling */
            PQclear(res);
        }
        else{    
            int rows = PQntuples(res); 
            for(int i=0; i<rows; i++) {
            strcpy(query, PQgetvalue(res, i, 0)); /*get Value */
            } 
        }
    }
    PQfinish(conn); /*closing the connection */
    return query;
}

/*initializaiton in begining of SNMP agent */
void
init_scalarValues(void)
{
    /* three OID's for three task */
    const oid hostVersionString_oid[] = { 1,3,6,1,4,1,53864,1,1 };
    const oid hostValueSnmpSignal_oid[] = { 1,3,6,1,4,1,53864,1,2 };
    const oid hostSizeDisk_oid[] = { 1,3,6,1,4,1,53864,1,3 };

  DEBUGMSGTL(("scalarValues", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("hostVersionString", handle_hostVersionString,
                               hostVersionString_oid, OID_LENGTH(hostVersionString_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("hostValueSnmpSignal", handle_hostValueSnmpSignal,
                               hostValueSnmpSignal_oid, OID_LENGTH(hostValueSnmpSignal_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("hostSizeDisk", handle_hostSizeDisk,
                               hostSizeDisk_oid, OID_LENGTH(hostSizeDisk_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_hostVersionString(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    strcpy(softwareVersion, "6.1.1"); /* string copied with  static value of 6.1.1 */
    switch(reqinfo->mode) {

        case MODE_GET:
        /*setter for setting snmp scalar to string variable */
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                    (u_char*) &softwareVersion,
                                     strlen(softwareVersion));

            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_hostVersionString\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_hostValueSnmpSignal(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    char *v;
    v = getSignalsValue(); 
    strcpy(snmpSignalValue, v); /*copying signalValue to v string */
    switch(reqinfo->mode) {
        /*setter for setting snmp scalar to string variable */
        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char*) &snmpSignalValue,
                                     strlen(snmpSignalValue));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_hostValueSnmpSignal\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_hostSizeDisk(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    char *val;
    val = getDiskSpace(); 
    strcpy(diskSpace,val);
    switch(reqinfo->mode) {
        
        /*setter for setting snmp scalar to string variable */
        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     (u_char*)diskSpace,
                                     strlen(diskSpace));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_hostSizeDisk\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
